title: <p align="center"> Vishakha Itankar </p>
logo: /assets/img/logo.png
description: 
<br>   
  I'm a technofunctional consulatant with 11 years of experience
 <br>
  
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
