title: <p align="center"> Vishakha Itankar </p>
logo: /assets/img/New Doc 2021-05-18_1.jpg
description: 
<br>   
  I'm a technofunctional consulatant with 11 years of experience in IT
 <br>
  
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
